name: CI/CD Microservicio Vehiculos

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ms-vehiculos   # el pom.xml está dentro de esta carpeta

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Dar permisos de ejecución al Maven Wrapper
      run: chmod +x mvnw

    - name: Build con Maven Wrapper
      run: ./mvnw clean install